---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/sectors":
    get:
      summary: list sectors
      responses:
        '200':
          description: successful
    patch:
      summary: update sector
      parameters: []
      responses:
        '200':
          description: Sector added successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      parameters: []
      responses:
        '200':
          description: User added successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                sector_name:
                  type: string
                agree:
                  type: boolean
              required:
              - name,
              - sector_name,
              - agree
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      parameters: []
      responses:
        '200':
          description: User added successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                sector_name:
                  type: string
                agree:
                  type: boolean
              required:
              - name
              - sector_name
              - agree
    put:
      summary: update user
      parameters: []
      responses:
        '200':
          description: User added successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                sector_name:
                  type: string
                agree:
                  type: boolean
              required:
              - name
              - sector_name
              - agree
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
